spring:
  datasource:
    url: jdbc:mysql://192.168.247.130:3306/mall_ums?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.130:8848

    alibaba:
      seata:
        tx-service-group: gulimall-member-group

  application:
    name: gulimall-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo