spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ums?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
        server-addr: localhost:8848

    alibaba:
      seata:
        tx-service-group: gulimall-member-group

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333

  application:
    name: gulimall-member

  thymeleaf:
    cache: false

  session:
    store-type: redis
  redis:
    host: localhost

  #服务追踪
  zipkin:
    base-url: http://localhost:9411/
    #关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    #指定以http的方式汇报数据
    sender:
      type: web
  #设置抽样采样率为100%，默认为0，1，即10%
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
