spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
        server-addr: localhost:8848

    alibaba:
      seata:
        tx-service-group: gulimall-product-group

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333

  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    suffix: .html

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

  #服务追踪
  zipkin:
    base-url: http://localhost:9411/
    #关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    #指定以http的方式汇报数据
    sender:
      type: web
  #设置抽样采样率为100%，默认为0，1，即10%
  sleuth:
    sampler:
      probability: 1

  #spring cache
  cache:
    type: redis
    redis:
      #设置缓存的数据的存活时间 (毫秒为单位)
      time-to-live: 36000
      #开启缓存前缀，如果没有指定前缀，默认使用缓存的名字作为前缀
      #spring.cache.redis.key-prefix=CACHE_
      use-key-prefix: true
      #是否缓存空值,解决缓存穿透问题
      cache-null-values: true

server:
  port: 11111
  servlet:
    session:
      timeout: 30m

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1      #全局逻辑删除规则
      logic-not-delete-value: 0

#配置日志级别
logging:
  level:
    #com.atguigu.gulimall: debug
    org.springframwork.openfeign: debug
    org.springframwork.sleuth: debug

alibaba:
  cloud:
    access-key: LTAI5tPvWggL1YSsjJc5VAiG
    secret-key: kWm2LVkawRU5z3c4Xv5HwDd4VVT2BM
#    oss:
#      endpoint: oss-cn-shanghai.aliyuncs.com

#解决json序列化的问题
seata:
  tx-service-group: gulimall-product-group
  client:
    undo:
      log-serialization: kryo
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      namespace: 244e55be-3e0b-48c1-b1ee-83722ed52b8f
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      namespace: 244e55be-3e0b-48c1-b1ee-83722ed52b8f
  service:
    vgroup-mapping:
      gulimall-product-group: default

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

feign:
  sentinel:
    enabled: true

