spring:
  datasource:
    url: jdbc:mysql://192.168.247.130:3306/mall_pms?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.130:8848

  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    suffix: .html

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1      #全局逻辑删除规则
      logic-not-delete-value: 0

server:
  port: 10000

#配置日志级别
#logging:
#  level:
#    com.atguigu.gulimall: debug

alibaba:
  cloud:
    access-key: LTAI5tPvWggL1YSsjJc5VAiG
    secret-key: kWm2LVkawRU5z3c4Xv5HwDd4VVT2BM
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com

