spring:
  datasource:
    url: jdbc:mysql://192.168.247.130:3306/mall_sms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
      server-addr: 119.3.151.37:8848

    alibaba:
      seata:
        tx-service-group: gulimall-coupon-group

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333

  application:
    name: gulimall-coupon

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo