spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.130:8848

    alibaba:
      seata:
        tx-service-group: gulimall-auth-server-group

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis # Session store type.

server:
  servlet:
    session:
      timeout: 30m

thymeleaf:
  cache: false
  suffix: .html

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo
