spring:
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
        server-addr: 119.3.151.37:8848

  application:
    name: gulimall-seckill

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    suffix: .html

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50 #默认最大大小Integer的最大值

server:
  port: 25000
  servlet:
    session:
      timeout: 30m

#配置日志级别
logging:
  level:
    com.atguigu.gulimall: debug


