spring:
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
        server-addr: localhost:8848

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333
        #client-ip: localhost

  application:
    name: gulimall-seckill

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    suffix: .html

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

  rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

  task:
    execution:
      pool:
        core-size: 5
        max-size: 50 #默认最大大小Integer的最大值

  #服务追踪
  zipkin:
    base-url: http://localhost:9411/
    #关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    #指定以http的方式汇报数据
    sender:
      type: web
  #设置抽样采样率为100%，默认为0，1，即10%
  sleuth:
    sampler:
      probability: 1

server:
  port: 25000
  servlet:
    session:
      timeout: 30m

#配置日志级别
logging:
  level:
    #com.atguigu.gulimall: debug
    org.springframwork.openfeign: debug
    org.springframwork.sleuth: debug

#'*'，代表开启全部监控，也可仅配置需要开启的监控，如： management.endpoints.web.exposure.include=beans,trace。
#management.endpoint.health.show-details=always，health endpoint开启显示全部细节。默认情况下/actuator/health是公开的，但不显示细节。
#management.endpoints.web.base-path=/monitor，启用指定的url地址访问根路径，默认路径为/actuator/*，开启则访问路径变为/monitor/*。
#management.endpoint.shutdown.enabled=true，启用接口关闭SpringBoot。
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true