spring:
  datasource:
    url: jdbc:mysql://192.168.247.130:3306/mall_oms?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
      server-addr: 119.3.151.37:8848

    alibaba:
      seata:
        tx-service-group: gulimall-order-group

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333

  thymeleaf:
    cache: false

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis

  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

  #服务追踪
  zipkin:
    base-url: http://119.3.151.37:9411/
    #关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    #指定以http的方式汇报数据
    sender:
      type: web
  #设置抽样采样率为100%，默认为0，1，即10%
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

#解决json序列化的问题
seata:
  tx-service-group: gulimall-order-group
  client:
    undo:
      log-serialization: kryo
  registry:
    type: nacos
    nacos:
      server-addr: 119.3.151.37:8848
      username: nacos
      password: nacos
      namespace: 244e55be-3e0b-48c1-b1ee-83722ed52b8f
  config:
    type: nacos
    nacos:
      server-addr: 119.3.151.37:8848
      username: nacos
      password: nacos
      namespace: 244e55be-3e0b-48c1-b1ee-83722ed52b8f
  service:
    vgroup-mapping:
      gulimall-order-group: default