spring:
  datasource:
    url: jdbc:mysql://192.168.247.130:3306/mall_oms?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
      server-addr: 119.3.151.37:8848

    alibaba:
      seata:
        tx-service-group: gulimall-order-group

  thymeleaf:
    cache: false

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis

  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

#解决json序列化的问题
seata:
    client:
      undo:
        log-serialization: kryo