server:
  port: 12000
  servlet:
    session:
      timeout: 30m

spring:
  cloud:
    nacos:
      server-addr: 192.168.247.130:8848

    alibaba:
      seata:
        tx-service-group: gulimall-search-group
  application:
    name: gulimall-search

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis

  thymeleaf:
    cache: false

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo
