server:
  port: 12000
  servlet:
    session:
      timeout: 30m

spring:
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
        server-addr: 119.3.151.37:8848

    alibaba:
      seata:
        tx-service-group: gulimall-search-group

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333

  application:
    name: gulimall-search

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis

  thymeleaf:
    cache: false

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo
