server:
  port: 12000
  servlet:
    session:
      timeout: 30m

spring:
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130:8848
        server-addr: 119.3.151.37:8848

    alibaba:
      seata:
        tx-service-group: gulimall-search-group

    sentinel:
      transport:
        port: 8719  #每一个微服务给控制台传输数据使用的端口
        dashboard: localhost:8333

  application:
    name: gulimall-search

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis

  #服务追踪
  zipkin:
    base-url: http://119.3.151.37:9411/
    #关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    #指定以http的方式汇报数据
    sender:
      type: web
  #设置抽样采样率为100%，默认为0，1，即10%
  sleuth:
    sampler:
      probability: 1

  thymeleaf:
    cache: false

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo
