spring:
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.247.130
        server-addr: 119.3.151.37:8848

    alibaba:
      seata:
        tx-service-group: gulimall-third-party-group
  application:
    name: gulimall-third-party

server:
  port: 30020

#解决json序列化的问题
seata:
  client:
    undo:
      log-serialization: kryo