spring:
  cloud:
    nacos:
      server-addr: 192.168.247.130
  application:
    name: gulimall-third-party

  alibaba:
    cloud:
      access-key: LTAI5tPvWggL1YSsjJc5VAiG
      secret-key: kWm2LVkawRU5z3c4Xv5HwDd4VVT2BM
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com

      #host: http://dingxin.market.alicloudapi.com
      host: https://dxyzm.market.alicloudapi.com
      path: /chuangxin/dxjk
      appcode: 5ea1072a0859486e8bd70afd833c6f04
      #tpl_id: TP1711063
server:
  port: 30000