spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.130:8848

  redis:
    host: 192.168.247.130
    port: 6379

  session:
    store-type: redis # Session store type.

server:
  servlet:
    session:
      timeout: 30m

  port: 30000

thymeleaf:
  cache: false
  suffix: .html
